- body_group: left_arm
  enabled: true
  priority: 200
  owner_source: demo_sender_single_chain_ik
  control_semantics: cartesian_absolute
  mode: single_chain_ik
  plugin: single_chain_ik_plugin
  backend: direct_backend
  active_plugins:
    - enabled: true
      type: single_chain_ik
      plugin_id: single_chain_ik_plugin
- body_group: right_arm
  enabled: true
  priority: 200
  owner_source: demo_sender_single_chain_ik
  control_semantics: cartesian_absolute
  mode: single_chain_ik
  plugin: single_chain_ik_plugin
  backend: direct_backend
  active_plugins:
    - enabled: true
      type: single_chain_ik
      plugin_id: single_chain_ik_plugin
