- plugin_id: direct_pass_plugin
  plugin: direct_pass
  enabled: false
- plugin_id: gmr_plugin
  plugin: gmr
  enabled: false
- plugin_id: single_chain_ik_plugin
  plugin: single_chain_ik
  enabled: true
- plugin_id: single_chain_ik_velocity_plugin
  plugin: single_chain_ik_velocity
  enabled: false
