enabled: true
chains:
  - body_group: left_arm
    ee_entity: left_wrist
    urdf_path: "assets/unitree_g1/g1_custom_collision_29dof.urdf"
    base_link: "torso_link"
    tip_link: "left_wrist_yaw_link"
    joint_names: [left_shoulder_pitch_joint, left_shoulder_roll_joint, left_shoulder_yaw_joint, left_elbow_joint, left_wrist_roll_joint, left_wrist_pitch_joint, left_wrist_yaw_joint]
    default_posture: [0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0]
    min_position_limit: [-3.0892, -1.5882, -2.6180, -1.0472, -1.972222054, -1.614429558, -1.614429558]
    max_position_limit: [2.6704, 2.2515, 2.6180, 2.0944, 1.972222054, 1.614429558, 1.614429558]
    max_iterations: 10000
    timeout_sec: 0.003
    epsilon: 0.00001
    random_restart: false
    perturbation_max_attempts: 5
    perturbation_position_range: 0.01
    perturbation_angle_deg_range: 5.0
  - body_group: right_arm
    ee_entity: right_wrist
    urdf_path: "assets/unitree_g1/g1_custom_collision_29dof.urdf"
    base_link: "torso_link"
    tip_link: "right_wrist_yaw_link"
    joint_names: [right_shoulder_pitch_joint, right_shoulder_roll_joint, right_shoulder_yaw_joint, right_elbow_joint, right_wrist_roll_joint, right_wrist_pitch_joint, right_wrist_yaw_joint]
    default_posture: [0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0]
    min_position_limit: [-3.0892, -2.2515, -2.6180, -1.0472, -1.972222054, -1.614429558, -1.614429558]
    max_position_limit: [2.6704, 1.5882, 2.6180, 2.0944, 1.972222054, 1.614429558, 1.614429558]
    max_iterations: 10000
    timeout_sec: 0.003
    epsilon: 0.00001
    random_restart: false
    perturbation_max_attempts: 5
    perturbation_position_range: 0.01
    perturbation_angle_deg_range: 5.0
