// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: puppet/uniform.proto

#include "puppet/uniform.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_puppet_2funiform_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_puppet_2funiform_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_puppet_2fcommon_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Timestamp_puppet_2fcommon_2eproto;
namespace puppet {
namespace puppet_proto {
class FrameContext_TagsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FrameContext_TagsEntry_DoNotUse> _instance;
} _FrameContext_TagsEntry_DoNotUse_default_instance_;
class FrameContextDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FrameContext> _instance;
} _FrameContext_default_instance_;
class PrimitiveMeta_TagsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PrimitiveMeta_TagsEntry_DoNotUse> _instance;
} _PrimitiveMeta_TagsEntry_DoNotUse_default_instance_;
class PrimitiveMetaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PrimitiveMeta> _instance;
} _PrimitiveMeta_default_instance_;
}  // namespace puppet_proto
}  // namespace puppet
static void InitDefaultsscc_info_FrameContext_puppet_2funiform_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::puppet::puppet_proto::_FrameContext_default_instance_;
    new (ptr) ::puppet::puppet_proto::FrameContext();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FrameContext_puppet_2funiform_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_FrameContext_puppet_2funiform_2eproto}, {
      &scc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto.base,}};

static void InitDefaultsscc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::puppet::puppet_proto::_FrameContext_TagsEntry_DoNotUse_default_instance_;
    new (ptr) ::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto}, {}};

static void InitDefaultsscc_info_PrimitiveMeta_puppet_2funiform_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::puppet::puppet_proto::_PrimitiveMeta_default_instance_;
    new (ptr) ::puppet::puppet_proto::PrimitiveMeta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_PrimitiveMeta_puppet_2funiform_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_PrimitiveMeta_puppet_2funiform_2eproto}, {
      &scc_info_Timestamp_puppet_2fcommon_2eproto.base,
      &scc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto.base,}};

static void InitDefaultsscc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::puppet::puppet_proto::_PrimitiveMeta_TagsEntry_DoNotUse_default_instance_;
    new (ptr) ::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_puppet_2funiform_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_puppet_2funiform_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_puppet_2funiform_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_puppet_2funiform_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, source_id_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, source_type_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, semantic_context_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, mode_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, robot_id_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, pipeline_id_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::FrameContext, tags_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, name_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, entity_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, body_group_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, frame_id_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, reference_frame_id_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, timestamp_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, confidence_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, valid_),
  PROTOBUF_FIELD_OFFSET(::puppet::puppet_proto::PrimitiveMeta, tags_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse)},
  { 9, -1, sizeof(::puppet::puppet_proto::FrameContext)},
  { 21, 28, sizeof(::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse)},
  { 30, -1, sizeof(::puppet::puppet_proto::PrimitiveMeta)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::puppet::puppet_proto::_FrameContext_TagsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::puppet::puppet_proto::_FrameContext_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::puppet::puppet_proto::_PrimitiveMeta_TagsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::puppet::puppet_proto::_PrimitiveMeta_default_instance_),
};

const char descriptor_table_protodef_puppet_2funiform_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024puppet/uniform.proto\022\023puppet.puppet_pr"
  "oto\032\023puppet/common.proto\"\216\002\n\014FrameContex"
  "t\022\021\n\tsource_id\030\001 \001(\t\0224\n\013source_type\030\002 \001("
  "\0162\037.puppet.puppet_proto.SourceType\022\030\n\020se"
  "mantic_context\030\003 \001(\t\022\014\n\004mode\030\004 \001(\t\022\020\n\010ro"
  "bot_id\030\005 \001(\t\022\023\n\013pipeline_id\030\006 \001(\t\0229\n\004tag"
  "s\030\024 \003(\0132+.puppet.puppet_proto.FrameConte"
  "xt.TagsEntry\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r"
  "\n\005value\030\002 \001(\t:\0028\001\"\316\002\n\rPrimitiveMeta\022\014\n\004n"
  "ame\030\001 \001(\t\022\016\n\006entity\030\002 \001(\t\0222\n\nbody_group\030"
  "\003 \001(\0162\036.puppet.puppet_proto.BodyGroup\022\020\n"
  "\010frame_id\030\004 \001(\t\022\032\n\022reference_frame_id\030\005 "
  "\001(\t\0221\n\ttimestamp\030\006 \001(\0132\036.puppet.puppet_p"
  "roto.Timestamp\022\022\n\nconfidence\030\007 \001(\002\022\r\n\005va"
  "lid\030\010 \001(\010\022:\n\004tags\030\024 \003(\0132,.puppet.puppet_"
  "proto.PrimitiveMeta.TagsEntry\032+\n\tTagsEnt"
  "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*\274\002\n\tB"
  "odyGroup\022\032\n\026BODY_GROUP_UNSPECIFIED\020\000\022\023\n\017"
  "BODY_GROUP_HEAD\020\001\022\027\n\023BODY_GROUP_LEFT_ARM"
  "\020\002\022\030\n\024BODY_GROUP_RIGHT_ARM\020\003\022\030\n\024BODY_GRO"
  "UP_BI_MANUAL\020\004\022\024\n\020BODY_GROUP_TORSO\020\005\022\023\n\017"
  "BODY_GROUP_BASE\020\006\022\031\n\025BODY_GROUP_LOWER_BO"
  "DY\020\007\022\031\n\025BODY_GROUP_WHOLE_BODY\020\010\022\033\n\027BODY_"
  "GROUP_LEFT_GRIPPER\020\t\022\034\n\030BODY_GROUP_RIGHT"
  "_GRIPPER\020\n\022\025\n\021BODY_GROUP_CUSTOM\020d*\274\001\n\nSo"
  "urceType\022\033\n\027SOURCE_TYPE_UNSPECIFIED\020\000\022\022\n"
  "\016SOURCE_TYPE_VR\020\001\022\032\n\026SOURCE_TYPE_MASTER_"
  "ARM\020\002\022\025\n\021SOURCE_TYPE_MOCAP\020\003\022\026\n\022SOURCE_T"
  "YPE_VISION\020\004\022\030\n\024SOURCE_TYPE_JOYSTICK\020\005\022\030"
  "\n\024SOURCE_TYPE_EXTERNAL\020db\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_puppet_2funiform_2eproto_deps[1] = {
  &::descriptor_table_puppet_2fcommon_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_puppet_2funiform_2eproto_sccs[4] = {
  &scc_info_FrameContext_puppet_2funiform_2eproto.base,
  &scc_info_FrameContext_TagsEntry_DoNotUse_puppet_2funiform_2eproto.base,
  &scc_info_PrimitiveMeta_puppet_2funiform_2eproto.base,
  &scc_info_PrimitiveMeta_TagsEntry_DoNotUse_puppet_2funiform_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_puppet_2funiform_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_puppet_2funiform_2eproto = {
  false, false, descriptor_table_protodef_puppet_2funiform_2eproto, "puppet/uniform.proto", 1192,
  &descriptor_table_puppet_2funiform_2eproto_once, descriptor_table_puppet_2funiform_2eproto_sccs, descriptor_table_puppet_2funiform_2eproto_deps, 4, 1,
  schemas, file_default_instances, TableStruct_puppet_2funiform_2eproto::offsets,
  file_level_metadata_puppet_2funiform_2eproto, 4, file_level_enum_descriptors_puppet_2funiform_2eproto, file_level_service_descriptors_puppet_2funiform_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_puppet_2funiform_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_puppet_2funiform_2eproto)), true);
namespace puppet {
namespace puppet_proto {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BodyGroup_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_puppet_2funiform_2eproto);
  return file_level_enum_descriptors_puppet_2funiform_2eproto[0];
}
bool BodyGroup_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 100:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SourceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_puppet_2funiform_2eproto);
  return file_level_enum_descriptors_puppet_2funiform_2eproto[1];
}
bool SourceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 100:
      return true;
    default:
      return false;
  }
}


// ===================================================================

FrameContext_TagsEntry_DoNotUse::FrameContext_TagsEntry_DoNotUse() {}
FrameContext_TagsEntry_DoNotUse::FrameContext_TagsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void FrameContext_TagsEntry_DoNotUse::MergeFrom(const FrameContext_TagsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata FrameContext_TagsEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void FrameContext_TagsEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class FrameContext::_Internal {
 public:
};

FrameContext::FrameContext(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  tags_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:puppet.puppet_proto.FrameContext)
}
FrameContext::FrameContext(const FrameContext& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  tags_.MergeFrom(from.tags_);
  source_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_source_id().empty()) {
    source_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_source_id(), 
      GetArena());
  }
  semantic_context_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_semantic_context().empty()) {
    semantic_context_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_semantic_context(), 
      GetArena());
  }
  mode_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_mode().empty()) {
    mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_mode(), 
      GetArena());
  }
  robot_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_robot_id().empty()) {
    robot_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_robot_id(), 
      GetArena());
  }
  pipeline_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pipeline_id().empty()) {
    pipeline_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pipeline_id(), 
      GetArena());
  }
  source_type_ = from.source_type_;
  // @@protoc_insertion_point(copy_constructor:puppet.puppet_proto.FrameContext)
}

void FrameContext::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FrameContext_puppet_2funiform_2eproto.base);
  source_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  semantic_context_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mode_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  robot_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pipeline_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  source_type_ = 0;
}

FrameContext::~FrameContext() {
  // @@protoc_insertion_point(destructor:puppet.puppet_proto.FrameContext)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FrameContext::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  source_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  semantic_context_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mode_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  robot_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pipeline_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FrameContext::ArenaDtor(void* object) {
  FrameContext* _this = reinterpret_cast< FrameContext* >(object);
  (void)_this;
}
void FrameContext::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FrameContext::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FrameContext& FrameContext::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FrameContext_puppet_2funiform_2eproto.base);
  return *internal_default_instance();
}


void FrameContext::Clear() {
// @@protoc_insertion_point(message_clear_start:puppet.puppet_proto.FrameContext)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tags_.Clear();
  source_id_.ClearToEmpty();
  semantic_context_.ClearToEmpty();
  mode_.ClearToEmpty();
  robot_id_.ClearToEmpty();
  pipeline_id_.ClearToEmpty();
  source_type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FrameContext::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string source_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_source_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.FrameContext.source_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .puppet.puppet_proto.SourceType source_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_source_type(static_cast<::puppet::puppet_proto::SourceType>(val));
        } else goto handle_unusual;
        continue;
      // string semantic_context = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_semantic_context();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.FrameContext.semantic_context"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string mode = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_mode();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.FrameContext.mode"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string robot_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_robot_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.FrameContext.robot_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string pipeline_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_pipeline_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.FrameContext.pipeline_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, string> tags = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(&tags_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<162>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FrameContext::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:puppet.puppet_proto.FrameContext)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string source_id = 1;
  if (this->source_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_source_id().data(), static_cast<int>(this->_internal_source_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.FrameContext.source_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_source_id(), target);
  }

  // .puppet.puppet_proto.SourceType source_type = 2;
  if (this->source_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_source_type(), target);
  }

  // string semantic_context = 3;
  if (this->semantic_context().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_semantic_context().data(), static_cast<int>(this->_internal_semantic_context().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.FrameContext.semantic_context");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_semantic_context(), target);
  }

  // string mode = 4;
  if (this->mode().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mode().data(), static_cast<int>(this->_internal_mode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.FrameContext.mode");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_mode(), target);
  }

  // string robot_id = 5;
  if (this->robot_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_robot_id().data(), static_cast<int>(this->_internal_robot_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.FrameContext.robot_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_robot_id(), target);
  }

  // string pipeline_id = 6;
  if (this->pipeline_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pipeline_id().data(), static_cast<int>(this->_internal_pipeline_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.FrameContext.pipeline_id");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_pipeline_id(), target);
  }

  // map<string, string> tags = 20;
  if (!this->_internal_tags().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "puppet.puppet_proto.FrameContext.TagsEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "puppet.puppet_proto.FrameContext.TagsEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_tags().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_tags().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_tags().begin();
          it != this->_internal_tags().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = FrameContext_TagsEntry_DoNotUse::Funcs::InternalSerialize(20, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_tags().begin();
          it != this->_internal_tags().end(); ++it) {
        target = FrameContext_TagsEntry_DoNotUse::Funcs::InternalSerialize(20, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:puppet.puppet_proto.FrameContext)
  return target;
}

size_t FrameContext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:puppet.puppet_proto.FrameContext)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> tags = 20;
  total_size += 2 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_tags_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_tags().begin();
      it != this->_internal_tags().end(); ++it) {
    total_size += FrameContext_TagsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string source_id = 1;
  if (this->source_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_source_id());
  }

  // string semantic_context = 3;
  if (this->semantic_context().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_semantic_context());
  }

  // string mode = 4;
  if (this->mode().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mode());
  }

  // string robot_id = 5;
  if (this->robot_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_robot_id());
  }

  // string pipeline_id = 6;
  if (this->pipeline_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pipeline_id());
  }

  // .puppet.puppet_proto.SourceType source_type = 2;
  if (this->source_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_source_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FrameContext::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:puppet.puppet_proto.FrameContext)
  GOOGLE_DCHECK_NE(&from, this);
  const FrameContext* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FrameContext>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:puppet.puppet_proto.FrameContext)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:puppet.puppet_proto.FrameContext)
    MergeFrom(*source);
  }
}

void FrameContext::MergeFrom(const FrameContext& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:puppet.puppet_proto.FrameContext)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tags_.MergeFrom(from.tags_);
  if (from.source_id().size() > 0) {
    _internal_set_source_id(from._internal_source_id());
  }
  if (from.semantic_context().size() > 0) {
    _internal_set_semantic_context(from._internal_semantic_context());
  }
  if (from.mode().size() > 0) {
    _internal_set_mode(from._internal_mode());
  }
  if (from.robot_id().size() > 0) {
    _internal_set_robot_id(from._internal_robot_id());
  }
  if (from.pipeline_id().size() > 0) {
    _internal_set_pipeline_id(from._internal_pipeline_id());
  }
  if (from.source_type() != 0) {
    _internal_set_source_type(from._internal_source_type());
  }
}

void FrameContext::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:puppet.puppet_proto.FrameContext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FrameContext::CopyFrom(const FrameContext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:puppet.puppet_proto.FrameContext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameContext::IsInitialized() const {
  return true;
}

void FrameContext::InternalSwap(FrameContext* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  tags_.Swap(&other->tags_);
  source_id_.Swap(&other->source_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  semantic_context_.Swap(&other->semantic_context_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  mode_.Swap(&other->mode_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  robot_id_.Swap(&other->robot_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  pipeline_id_.Swap(&other->pipeline_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(source_type_, other->source_type_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FrameContext::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

PrimitiveMeta_TagsEntry_DoNotUse::PrimitiveMeta_TagsEntry_DoNotUse() {}
PrimitiveMeta_TagsEntry_DoNotUse::PrimitiveMeta_TagsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PrimitiveMeta_TagsEntry_DoNotUse::MergeFrom(const PrimitiveMeta_TagsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PrimitiveMeta_TagsEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void PrimitiveMeta_TagsEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class PrimitiveMeta::_Internal {
 public:
  static const ::puppet::puppet_proto::Timestamp& timestamp(const PrimitiveMeta* msg);
};

const ::puppet::puppet_proto::Timestamp&
PrimitiveMeta::_Internal::timestamp(const PrimitiveMeta* msg) {
  return *msg->timestamp_;
}
void PrimitiveMeta::clear_timestamp() {
  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
PrimitiveMeta::PrimitiveMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  tags_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:puppet.puppet_proto.PrimitiveMeta)
}
PrimitiveMeta::PrimitiveMeta(const PrimitiveMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  tags_.MergeFrom(from.tags_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  entity_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_entity().empty()) {
    entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_entity(), 
      GetArena());
  }
  frame_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_frame_id().empty()) {
    frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_frame_id(), 
      GetArena());
  }
  reference_frame_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reference_frame_id().empty()) {
    reference_frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_reference_frame_id(), 
      GetArena());
  }
  if (from._internal_has_timestamp()) {
    timestamp_ = new ::puppet::puppet_proto::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = nullptr;
  }
  ::memcpy(&body_group_, &from.body_group_,
    static_cast<size_t>(reinterpret_cast<char*>(&valid_) -
    reinterpret_cast<char*>(&body_group_)) + sizeof(valid_));
  // @@protoc_insertion_point(copy_constructor:puppet.puppet_proto.PrimitiveMeta)
}

void PrimitiveMeta::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PrimitiveMeta_puppet_2funiform_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  entity_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  frame_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reference_frame_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&timestamp_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&valid_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(valid_));
}

PrimitiveMeta::~PrimitiveMeta() {
  // @@protoc_insertion_point(destructor:puppet.puppet_proto.PrimitiveMeta)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PrimitiveMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  entity_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  frame_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reference_frame_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete timestamp_;
}

void PrimitiveMeta::ArenaDtor(void* object) {
  PrimitiveMeta* _this = reinterpret_cast< PrimitiveMeta* >(object);
  (void)_this;
}
void PrimitiveMeta::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PrimitiveMeta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PrimitiveMeta& PrimitiveMeta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PrimitiveMeta_puppet_2funiform_2eproto.base);
  return *internal_default_instance();
}


void PrimitiveMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:puppet.puppet_proto.PrimitiveMeta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tags_.Clear();
  name_.ClearToEmpty();
  entity_.ClearToEmpty();
  frame_id_.ClearToEmpty();
  reference_frame_id_.ClearToEmpty();
  if (GetArena() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
  ::memset(&body_group_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&valid_) -
      reinterpret_cast<char*>(&body_group_)) + sizeof(valid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PrimitiveMeta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.PrimitiveMeta.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string entity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_entity();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.PrimitiveMeta.entity"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .puppet.puppet_proto.BodyGroup body_group = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_body_group(static_cast<::puppet::puppet_proto::BodyGroup>(val));
        } else goto handle_unusual;
        continue;
      // string frame_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_frame_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.PrimitiveMeta.frame_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reference_frame_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_reference_frame_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "puppet.puppet_proto.PrimitiveMeta.reference_frame_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .puppet.puppet_proto.Timestamp timestamp = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float confidence = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          confidence_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // bool valid = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          valid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, string> tags = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr -= 2;
          do {
            ptr += 2;
            ptr = ctx->ParseMessage(&tags_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<162>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PrimitiveMeta::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:puppet.puppet_proto.PrimitiveMeta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.PrimitiveMeta.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string entity = 2;
  if (this->entity().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_entity().data(), static_cast<int>(this->_internal_entity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.PrimitiveMeta.entity");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_entity(), target);
  }

  // .puppet.puppet_proto.BodyGroup body_group = 3;
  if (this->body_group() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_body_group(), target);
  }

  // string frame_id = 4;
  if (this->frame_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_frame_id().data(), static_cast<int>(this->_internal_frame_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.PrimitiveMeta.frame_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_frame_id(), target);
  }

  // string reference_frame_id = 5;
  if (this->reference_frame_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reference_frame_id().data(), static_cast<int>(this->_internal_reference_frame_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "puppet.puppet_proto.PrimitiveMeta.reference_frame_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_reference_frame_id(), target);
  }

  // .puppet.puppet_proto.Timestamp timestamp = 6;
  if (this->has_timestamp()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::timestamp(this), target, stream);
  }

  // float confidence = 7;
  if (!(this->confidence() <= 0 && this->confidence() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_confidence(), target);
  }

  // bool valid = 8;
  if (this->valid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(8, this->_internal_valid(), target);
  }

  // map<string, string> tags = 20;
  if (!this->_internal_tags().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "puppet.puppet_proto.PrimitiveMeta.TagsEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "puppet.puppet_proto.PrimitiveMeta.TagsEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_tags().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_tags().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_tags().begin();
          it != this->_internal_tags().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = PrimitiveMeta_TagsEntry_DoNotUse::Funcs::InternalSerialize(20, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_tags().begin();
          it != this->_internal_tags().end(); ++it) {
        target = PrimitiveMeta_TagsEntry_DoNotUse::Funcs::InternalSerialize(20, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:puppet.puppet_proto.PrimitiveMeta)
  return target;
}

size_t PrimitiveMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:puppet.puppet_proto.PrimitiveMeta)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> tags = 20;
  total_size += 2 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_tags_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_tags().begin();
      it != this->_internal_tags().end(); ++it) {
    total_size += PrimitiveMeta_TagsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string entity = 2;
  if (this->entity().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_entity());
  }

  // string frame_id = 4;
  if (this->frame_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_frame_id());
  }

  // string reference_frame_id = 5;
  if (this->reference_frame_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reference_frame_id());
  }

  // .puppet.puppet_proto.Timestamp timestamp = 6;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .puppet.puppet_proto.BodyGroup body_group = 3;
  if (this->body_group() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_body_group());
  }

  // float confidence = 7;
  if (!(this->confidence() <= 0 && this->confidence() >= 0)) {
    total_size += 1 + 4;
  }

  // bool valid = 8;
  if (this->valid() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PrimitiveMeta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:puppet.puppet_proto.PrimitiveMeta)
  GOOGLE_DCHECK_NE(&from, this);
  const PrimitiveMeta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PrimitiveMeta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:puppet.puppet_proto.PrimitiveMeta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:puppet.puppet_proto.PrimitiveMeta)
    MergeFrom(*source);
  }
}

void PrimitiveMeta::MergeFrom(const PrimitiveMeta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:puppet.puppet_proto.PrimitiveMeta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tags_.MergeFrom(from.tags_);
  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.entity().size() > 0) {
    _internal_set_entity(from._internal_entity());
  }
  if (from.frame_id().size() > 0) {
    _internal_set_frame_id(from._internal_frame_id());
  }
  if (from.reference_frame_id().size() > 0) {
    _internal_set_reference_frame_id(from._internal_reference_frame_id());
  }
  if (from.has_timestamp()) {
    _internal_mutable_timestamp()->::puppet::puppet_proto::Timestamp::MergeFrom(from._internal_timestamp());
  }
  if (from.body_group() != 0) {
    _internal_set_body_group(from._internal_body_group());
  }
  if (!(from.confidence() <= 0 && from.confidence() >= 0)) {
    _internal_set_confidence(from._internal_confidence());
  }
  if (from.valid() != 0) {
    _internal_set_valid(from._internal_valid());
  }
}

void PrimitiveMeta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:puppet.puppet_proto.PrimitiveMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrimitiveMeta::CopyFrom(const PrimitiveMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:puppet.puppet_proto.PrimitiveMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrimitiveMeta::IsInitialized() const {
  return true;
}

void PrimitiveMeta::InternalSwap(PrimitiveMeta* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  tags_.Swap(&other->tags_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  entity_.Swap(&other->entity_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  frame_id_.Swap(&other->frame_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  reference_frame_id_.Swap(&other->reference_frame_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PrimitiveMeta, valid_)
      + sizeof(PrimitiveMeta::valid_)
      - PROTOBUF_FIELD_OFFSET(PrimitiveMeta, timestamp_)>(
          reinterpret_cast<char*>(&timestamp_),
          reinterpret_cast<char*>(&other->timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PrimitiveMeta::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace puppet_proto
}  // namespace puppet
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse* Arena::CreateMaybeMessage< ::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::puppet::puppet_proto::FrameContext* Arena::CreateMaybeMessage< ::puppet::puppet_proto::FrameContext >(Arena* arena) {
  return Arena::CreateMessageInternal< ::puppet::puppet_proto::FrameContext >(arena);
}
template<> PROTOBUF_NOINLINE ::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse* Arena::CreateMaybeMessage< ::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::puppet::puppet_proto::PrimitiveMeta* Arena::CreateMaybeMessage< ::puppet::puppet_proto::PrimitiveMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::puppet::puppet_proto::PrimitiveMeta >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
