// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: puppet/uniform.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_puppet_2funiform_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_puppet_2funiform_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "puppet/common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_puppet_2funiform_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_puppet_2funiform_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_puppet_2funiform_2eproto;
namespace puppet {
namespace puppet_proto {
class FrameContext;
class FrameContextDefaultTypeInternal;
extern FrameContextDefaultTypeInternal _FrameContext_default_instance_;
class FrameContext_TagsEntry_DoNotUse;
class FrameContext_TagsEntry_DoNotUseDefaultTypeInternal;
extern FrameContext_TagsEntry_DoNotUseDefaultTypeInternal _FrameContext_TagsEntry_DoNotUse_default_instance_;
class PrimitiveMeta;
class PrimitiveMetaDefaultTypeInternal;
extern PrimitiveMetaDefaultTypeInternal _PrimitiveMeta_default_instance_;
class PrimitiveMeta_TagsEntry_DoNotUse;
class PrimitiveMeta_TagsEntry_DoNotUseDefaultTypeInternal;
extern PrimitiveMeta_TagsEntry_DoNotUseDefaultTypeInternal _PrimitiveMeta_TagsEntry_DoNotUse_default_instance_;
}  // namespace puppet_proto
}  // namespace puppet
PROTOBUF_NAMESPACE_OPEN
template<> ::puppet::puppet_proto::FrameContext* Arena::CreateMaybeMessage<::puppet::puppet_proto::FrameContext>(Arena*);
template<> ::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse* Arena::CreateMaybeMessage<::puppet::puppet_proto::FrameContext_TagsEntry_DoNotUse>(Arena*);
template<> ::puppet::puppet_proto::PrimitiveMeta* Arena::CreateMaybeMessage<::puppet::puppet_proto::PrimitiveMeta>(Arena*);
template<> ::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse* Arena::CreateMaybeMessage<::puppet::puppet_proto::PrimitiveMeta_TagsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace puppet {
namespace puppet_proto {

enum BodyGroup : int {
  BODY_GROUP_UNSPECIFIED = 0,
  BODY_GROUP_HEAD = 1,
  BODY_GROUP_LEFT_ARM = 2,
  BODY_GROUP_RIGHT_ARM = 3,
  BODY_GROUP_BI_MANUAL = 4,
  BODY_GROUP_TORSO = 5,
  BODY_GROUP_BASE = 6,
  BODY_GROUP_LOWER_BODY = 7,
  BODY_GROUP_WHOLE_BODY = 8,
  BODY_GROUP_LEFT_GRIPPER = 9,
  BODY_GROUP_RIGHT_GRIPPER = 10,
  BODY_GROUP_CUSTOM = 100,
  BodyGroup_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  BodyGroup_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool BodyGroup_IsValid(int value);
constexpr BodyGroup BodyGroup_MIN = BODY_GROUP_UNSPECIFIED;
constexpr BodyGroup BodyGroup_MAX = BODY_GROUP_CUSTOM;
constexpr int BodyGroup_ARRAYSIZE = BodyGroup_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* BodyGroup_descriptor();
template<typename T>
inline const std::string& BodyGroup_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BodyGroup>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BodyGroup_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    BodyGroup_descriptor(), enum_t_value);
}
inline bool BodyGroup_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BodyGroup* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<BodyGroup>(
    BodyGroup_descriptor(), name, value);
}
enum SourceType : int {
  SOURCE_TYPE_UNSPECIFIED = 0,
  SOURCE_TYPE_VR = 1,
  SOURCE_TYPE_MASTER_ARM = 2,
  SOURCE_TYPE_MOCAP = 3,
  SOURCE_TYPE_VISION = 4,
  SOURCE_TYPE_JOYSTICK = 5,
  SOURCE_TYPE_EXTERNAL = 100,
  SourceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SourceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SourceType_IsValid(int value);
constexpr SourceType SourceType_MIN = SOURCE_TYPE_UNSPECIFIED;
constexpr SourceType SourceType_MAX = SOURCE_TYPE_EXTERNAL;
constexpr int SourceType_ARRAYSIZE = SourceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SourceType_descriptor();
template<typename T>
inline const std::string& SourceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SourceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SourceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SourceType_descriptor(), enum_t_value);
}
inline bool SourceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SourceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SourceType>(
    SourceType_descriptor(), name, value);
}
// ===================================================================

class FrameContext_TagsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FrameContext_TagsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FrameContext_TagsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  FrameContext_TagsEntry_DoNotUse();
  explicit FrameContext_TagsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const FrameContext_TagsEntry_DoNotUse& other);
  static const FrameContext_TagsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const FrameContext_TagsEntry_DoNotUse*>(&_FrameContext_TagsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "puppet.puppet_proto.FrameContext.TagsEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "puppet.puppet_proto.FrameContext.TagsEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_puppet_2funiform_2eproto);
    return ::descriptor_table_puppet_2funiform_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class FrameContext PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:puppet.puppet_proto.FrameContext) */ {
 public:
  inline FrameContext() : FrameContext(nullptr) {}
  virtual ~FrameContext();

  FrameContext(const FrameContext& from);
  FrameContext(FrameContext&& from) noexcept
    : FrameContext() {
    *this = ::std::move(from);
  }

  inline FrameContext& operator=(const FrameContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameContext& operator=(FrameContext&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FrameContext& default_instance();

  static inline const FrameContext* internal_default_instance() {
    return reinterpret_cast<const FrameContext*>(
               &_FrameContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FrameContext& a, FrameContext& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameContext* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameContext* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FrameContext* New() const final {
    return CreateMaybeMessage<FrameContext>(nullptr);
  }

  FrameContext* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FrameContext>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FrameContext& from);
  void MergeFrom(const FrameContext& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameContext* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "puppet.puppet_proto.FrameContext";
  }
  protected:
  explicit FrameContext(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_puppet_2funiform_2eproto);
    return ::descriptor_table_puppet_2funiform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kTagsFieldNumber = 20,
    kSourceIdFieldNumber = 1,
    kSemanticContextFieldNumber = 3,
    kModeFieldNumber = 4,
    kRobotIdFieldNumber = 5,
    kPipelineIdFieldNumber = 6,
    kSourceTypeFieldNumber = 2,
  };
  // map<string, string> tags = 20;
  int tags_size() const;
  private:
  int _internal_tags_size() const;
  public:
  void clear_tags();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_tags() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_tags();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      tags() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_tags();

  // string source_id = 1;
  void clear_source_id();
  const std::string& source_id() const;
  void set_source_id(const std::string& value);
  void set_source_id(std::string&& value);
  void set_source_id(const char* value);
  void set_source_id(const char* value, size_t size);
  std::string* mutable_source_id();
  std::string* release_source_id();
  void set_allocated_source_id(std::string* source_id);
  private:
  const std::string& _internal_source_id() const;
  void _internal_set_source_id(const std::string& value);
  std::string* _internal_mutable_source_id();
  public:

  // string semantic_context = 3;
  void clear_semantic_context();
  const std::string& semantic_context() const;
  void set_semantic_context(const std::string& value);
  void set_semantic_context(std::string&& value);
  void set_semantic_context(const char* value);
  void set_semantic_context(const char* value, size_t size);
  std::string* mutable_semantic_context();
  std::string* release_semantic_context();
  void set_allocated_semantic_context(std::string* semantic_context);
  private:
  const std::string& _internal_semantic_context() const;
  void _internal_set_semantic_context(const std::string& value);
  std::string* _internal_mutable_semantic_context();
  public:

  // string mode = 4;
  void clear_mode();
  const std::string& mode() const;
  void set_mode(const std::string& value);
  void set_mode(std::string&& value);
  void set_mode(const char* value);
  void set_mode(const char* value, size_t size);
  std::string* mutable_mode();
  std::string* release_mode();
  void set_allocated_mode(std::string* mode);
  private:
  const std::string& _internal_mode() const;
  void _internal_set_mode(const std::string& value);
  std::string* _internal_mutable_mode();
  public:

  // string robot_id = 5;
  void clear_robot_id();
  const std::string& robot_id() const;
  void set_robot_id(const std::string& value);
  void set_robot_id(std::string&& value);
  void set_robot_id(const char* value);
  void set_robot_id(const char* value, size_t size);
  std::string* mutable_robot_id();
  std::string* release_robot_id();
  void set_allocated_robot_id(std::string* robot_id);
  private:
  const std::string& _internal_robot_id() const;
  void _internal_set_robot_id(const std::string& value);
  std::string* _internal_mutable_robot_id();
  public:

  // string pipeline_id = 6;
  void clear_pipeline_id();
  const std::string& pipeline_id() const;
  void set_pipeline_id(const std::string& value);
  void set_pipeline_id(std::string&& value);
  void set_pipeline_id(const char* value);
  void set_pipeline_id(const char* value, size_t size);
  std::string* mutable_pipeline_id();
  std::string* release_pipeline_id();
  void set_allocated_pipeline_id(std::string* pipeline_id);
  private:
  const std::string& _internal_pipeline_id() const;
  void _internal_set_pipeline_id(const std::string& value);
  std::string* _internal_mutable_pipeline_id();
  public:

  // .puppet.puppet_proto.SourceType source_type = 2;
  void clear_source_type();
  ::puppet::puppet_proto::SourceType source_type() const;
  void set_source_type(::puppet::puppet_proto::SourceType value);
  private:
  ::puppet::puppet_proto::SourceType _internal_source_type() const;
  void _internal_set_source_type(::puppet::puppet_proto::SourceType value);
  public:

  // @@protoc_insertion_point(class_scope:puppet.puppet_proto.FrameContext)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      FrameContext_TagsEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> tags_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr semantic_context_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mode_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr robot_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pipeline_id_;
  int source_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_puppet_2funiform_2eproto;
};
// -------------------------------------------------------------------

class PrimitiveMeta_TagsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PrimitiveMeta_TagsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PrimitiveMeta_TagsEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  PrimitiveMeta_TagsEntry_DoNotUse();
  explicit PrimitiveMeta_TagsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PrimitiveMeta_TagsEntry_DoNotUse& other);
  static const PrimitiveMeta_TagsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PrimitiveMeta_TagsEntry_DoNotUse*>(&_PrimitiveMeta_TagsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "puppet.puppet_proto.PrimitiveMeta.TagsEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "puppet.puppet_proto.PrimitiveMeta.TagsEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_puppet_2funiform_2eproto);
    return ::descriptor_table_puppet_2funiform_2eproto.file_level_metadata[2];
  }

  public:
};

// -------------------------------------------------------------------

class PrimitiveMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:puppet.puppet_proto.PrimitiveMeta) */ {
 public:
  inline PrimitiveMeta() : PrimitiveMeta(nullptr) {}
  virtual ~PrimitiveMeta();

  PrimitiveMeta(const PrimitiveMeta& from);
  PrimitiveMeta(PrimitiveMeta&& from) noexcept
    : PrimitiveMeta() {
    *this = ::std::move(from);
  }

  inline PrimitiveMeta& operator=(const PrimitiveMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrimitiveMeta& operator=(PrimitiveMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrimitiveMeta& default_instance();

  static inline const PrimitiveMeta* internal_default_instance() {
    return reinterpret_cast<const PrimitiveMeta*>(
               &_PrimitiveMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PrimitiveMeta& a, PrimitiveMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(PrimitiveMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimitiveMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrimitiveMeta* New() const final {
    return CreateMaybeMessage<PrimitiveMeta>(nullptr);
  }

  PrimitiveMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrimitiveMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrimitiveMeta& from);
  void MergeFrom(const PrimitiveMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrimitiveMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "puppet.puppet_proto.PrimitiveMeta";
  }
  protected:
  explicit PrimitiveMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_puppet_2funiform_2eproto);
    return ::descriptor_table_puppet_2funiform_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kTagsFieldNumber = 20,
    kNameFieldNumber = 1,
    kEntityFieldNumber = 2,
    kFrameIdFieldNumber = 4,
    kReferenceFrameIdFieldNumber = 5,
    kTimestampFieldNumber = 6,
    kBodyGroupFieldNumber = 3,
    kConfidenceFieldNumber = 7,
    kValidFieldNumber = 8,
  };
  // map<string, string> tags = 20;
  int tags_size() const;
  private:
  int _internal_tags_size() const;
  public:
  void clear_tags();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_tags() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_tags();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      tags() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_tags();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string entity = 2;
  void clear_entity();
  const std::string& entity() const;
  void set_entity(const std::string& value);
  void set_entity(std::string&& value);
  void set_entity(const char* value);
  void set_entity(const char* value, size_t size);
  std::string* mutable_entity();
  std::string* release_entity();
  void set_allocated_entity(std::string* entity);
  private:
  const std::string& _internal_entity() const;
  void _internal_set_entity(const std::string& value);
  std::string* _internal_mutable_entity();
  public:

  // string frame_id = 4;
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // string reference_frame_id = 5;
  void clear_reference_frame_id();
  const std::string& reference_frame_id() const;
  void set_reference_frame_id(const std::string& value);
  void set_reference_frame_id(std::string&& value);
  void set_reference_frame_id(const char* value);
  void set_reference_frame_id(const char* value, size_t size);
  std::string* mutable_reference_frame_id();
  std::string* release_reference_frame_id();
  void set_allocated_reference_frame_id(std::string* reference_frame_id);
  private:
  const std::string& _internal_reference_frame_id() const;
  void _internal_set_reference_frame_id(const std::string& value);
  std::string* _internal_mutable_reference_frame_id();
  public:

  // .puppet.puppet_proto.Timestamp timestamp = 6;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const ::puppet::puppet_proto::Timestamp& timestamp() const;
  ::puppet::puppet_proto::Timestamp* release_timestamp();
  ::puppet::puppet_proto::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::puppet::puppet_proto::Timestamp* timestamp);
  private:
  const ::puppet::puppet_proto::Timestamp& _internal_timestamp() const;
  ::puppet::puppet_proto::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      ::puppet::puppet_proto::Timestamp* timestamp);
  ::puppet::puppet_proto::Timestamp* unsafe_arena_release_timestamp();

  // .puppet.puppet_proto.BodyGroup body_group = 3;
  void clear_body_group();
  ::puppet::puppet_proto::BodyGroup body_group() const;
  void set_body_group(::puppet::puppet_proto::BodyGroup value);
  private:
  ::puppet::puppet_proto::BodyGroup _internal_body_group() const;
  void _internal_set_body_group(::puppet::puppet_proto::BodyGroup value);
  public:

  // float confidence = 7;
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // bool valid = 8;
  void clear_valid();
  bool valid() const;
  void set_valid(bool value);
  private:
  bool _internal_valid() const;
  void _internal_set_valid(bool value);
  public:

  // @@protoc_insertion_point(class_scope:puppet.puppet_proto.PrimitiveMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      PrimitiveMeta_TagsEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> tags_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr entity_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reference_frame_id_;
  ::puppet::puppet_proto::Timestamp* timestamp_;
  int body_group_;
  float confidence_;
  bool valid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_puppet_2funiform_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FrameContext

// string source_id = 1;
inline void FrameContext::clear_source_id() {
  source_id_.ClearToEmpty();
}
inline const std::string& FrameContext::source_id() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.source_id)
  return _internal_source_id();
}
inline void FrameContext::set_source_id(const std::string& value) {
  _internal_set_source_id(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.source_id)
}
inline std::string* FrameContext::mutable_source_id() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.FrameContext.source_id)
  return _internal_mutable_source_id();
}
inline const std::string& FrameContext::_internal_source_id() const {
  return source_id_.Get();
}
inline void FrameContext::_internal_set_source_id(const std::string& value) {
  
  source_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FrameContext::set_source_id(std::string&& value) {
  
  source_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.FrameContext.source_id)
}
inline void FrameContext::set_source_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  source_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.FrameContext.source_id)
}
inline void FrameContext::set_source_id(const char* value,
    size_t size) {
  
  source_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.FrameContext.source_id)
}
inline std::string* FrameContext::_internal_mutable_source_id() {
  
  return source_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FrameContext::release_source_id() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.FrameContext.source_id)
  return source_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameContext::set_allocated_source_id(std::string* source_id) {
  if (source_id != nullptr) {
    
  } else {
    
  }
  source_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), source_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.FrameContext.source_id)
}

// .puppet.puppet_proto.SourceType source_type = 2;
inline void FrameContext::clear_source_type() {
  source_type_ = 0;
}
inline ::puppet::puppet_proto::SourceType FrameContext::_internal_source_type() const {
  return static_cast< ::puppet::puppet_proto::SourceType >(source_type_);
}
inline ::puppet::puppet_proto::SourceType FrameContext::source_type() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.source_type)
  return _internal_source_type();
}
inline void FrameContext::_internal_set_source_type(::puppet::puppet_proto::SourceType value) {
  
  source_type_ = value;
}
inline void FrameContext::set_source_type(::puppet::puppet_proto::SourceType value) {
  _internal_set_source_type(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.source_type)
}

// string semantic_context = 3;
inline void FrameContext::clear_semantic_context() {
  semantic_context_.ClearToEmpty();
}
inline const std::string& FrameContext::semantic_context() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.semantic_context)
  return _internal_semantic_context();
}
inline void FrameContext::set_semantic_context(const std::string& value) {
  _internal_set_semantic_context(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.semantic_context)
}
inline std::string* FrameContext::mutable_semantic_context() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.FrameContext.semantic_context)
  return _internal_mutable_semantic_context();
}
inline const std::string& FrameContext::_internal_semantic_context() const {
  return semantic_context_.Get();
}
inline void FrameContext::_internal_set_semantic_context(const std::string& value) {
  
  semantic_context_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FrameContext::set_semantic_context(std::string&& value) {
  
  semantic_context_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.FrameContext.semantic_context)
}
inline void FrameContext::set_semantic_context(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  semantic_context_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.FrameContext.semantic_context)
}
inline void FrameContext::set_semantic_context(const char* value,
    size_t size) {
  
  semantic_context_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.FrameContext.semantic_context)
}
inline std::string* FrameContext::_internal_mutable_semantic_context() {
  
  return semantic_context_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FrameContext::release_semantic_context() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.FrameContext.semantic_context)
  return semantic_context_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameContext::set_allocated_semantic_context(std::string* semantic_context) {
  if (semantic_context != nullptr) {
    
  } else {
    
  }
  semantic_context_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), semantic_context,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.FrameContext.semantic_context)
}

// string mode = 4;
inline void FrameContext::clear_mode() {
  mode_.ClearToEmpty();
}
inline const std::string& FrameContext::mode() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.mode)
  return _internal_mode();
}
inline void FrameContext::set_mode(const std::string& value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.mode)
}
inline std::string* FrameContext::mutable_mode() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.FrameContext.mode)
  return _internal_mutable_mode();
}
inline const std::string& FrameContext::_internal_mode() const {
  return mode_.Get();
}
inline void FrameContext::_internal_set_mode(const std::string& value) {
  
  mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FrameContext::set_mode(std::string&& value) {
  
  mode_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.FrameContext.mode)
}
inline void FrameContext::set_mode(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.FrameContext.mode)
}
inline void FrameContext::set_mode(const char* value,
    size_t size) {
  
  mode_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.FrameContext.mode)
}
inline std::string* FrameContext::_internal_mutable_mode() {
  
  return mode_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FrameContext::release_mode() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.FrameContext.mode)
  return mode_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameContext::set_allocated_mode(std::string* mode) {
  if (mode != nullptr) {
    
  } else {
    
  }
  mode_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mode,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.FrameContext.mode)
}

// string robot_id = 5;
inline void FrameContext::clear_robot_id() {
  robot_id_.ClearToEmpty();
}
inline const std::string& FrameContext::robot_id() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.robot_id)
  return _internal_robot_id();
}
inline void FrameContext::set_robot_id(const std::string& value) {
  _internal_set_robot_id(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.robot_id)
}
inline std::string* FrameContext::mutable_robot_id() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.FrameContext.robot_id)
  return _internal_mutable_robot_id();
}
inline const std::string& FrameContext::_internal_robot_id() const {
  return robot_id_.Get();
}
inline void FrameContext::_internal_set_robot_id(const std::string& value) {
  
  robot_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FrameContext::set_robot_id(std::string&& value) {
  
  robot_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.FrameContext.robot_id)
}
inline void FrameContext::set_robot_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  robot_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.FrameContext.robot_id)
}
inline void FrameContext::set_robot_id(const char* value,
    size_t size) {
  
  robot_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.FrameContext.robot_id)
}
inline std::string* FrameContext::_internal_mutable_robot_id() {
  
  return robot_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FrameContext::release_robot_id() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.FrameContext.robot_id)
  return robot_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameContext::set_allocated_robot_id(std::string* robot_id) {
  if (robot_id != nullptr) {
    
  } else {
    
  }
  robot_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), robot_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.FrameContext.robot_id)
}

// string pipeline_id = 6;
inline void FrameContext::clear_pipeline_id() {
  pipeline_id_.ClearToEmpty();
}
inline const std::string& FrameContext::pipeline_id() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.FrameContext.pipeline_id)
  return _internal_pipeline_id();
}
inline void FrameContext::set_pipeline_id(const std::string& value) {
  _internal_set_pipeline_id(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.FrameContext.pipeline_id)
}
inline std::string* FrameContext::mutable_pipeline_id() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.FrameContext.pipeline_id)
  return _internal_mutable_pipeline_id();
}
inline const std::string& FrameContext::_internal_pipeline_id() const {
  return pipeline_id_.Get();
}
inline void FrameContext::_internal_set_pipeline_id(const std::string& value) {
  
  pipeline_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void FrameContext::set_pipeline_id(std::string&& value) {
  
  pipeline_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.FrameContext.pipeline_id)
}
inline void FrameContext::set_pipeline_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pipeline_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.FrameContext.pipeline_id)
}
inline void FrameContext::set_pipeline_id(const char* value,
    size_t size) {
  
  pipeline_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.FrameContext.pipeline_id)
}
inline std::string* FrameContext::_internal_mutable_pipeline_id() {
  
  return pipeline_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* FrameContext::release_pipeline_id() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.FrameContext.pipeline_id)
  return pipeline_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FrameContext::set_allocated_pipeline_id(std::string* pipeline_id) {
  if (pipeline_id != nullptr) {
    
  } else {
    
  }
  pipeline_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pipeline_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.FrameContext.pipeline_id)
}

// map<string, string> tags = 20;
inline int FrameContext::_internal_tags_size() const {
  return tags_.size();
}
inline int FrameContext::tags_size() const {
  return _internal_tags_size();
}
inline void FrameContext::clear_tags() {
  tags_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
FrameContext::_internal_tags() const {
  return tags_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
FrameContext::tags() const {
  // @@protoc_insertion_point(field_map:puppet.puppet_proto.FrameContext.tags)
  return _internal_tags();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
FrameContext::_internal_mutable_tags() {
  return tags_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
FrameContext::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_map:puppet.puppet_proto.FrameContext.tags)
  return _internal_mutable_tags();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PrimitiveMeta

// string name = 1;
inline void PrimitiveMeta::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& PrimitiveMeta::name() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.name)
  return _internal_name();
}
inline void PrimitiveMeta::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.name)
}
inline std::string* PrimitiveMeta::mutable_name() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.PrimitiveMeta.name)
  return _internal_mutable_name();
}
inline const std::string& PrimitiveMeta::_internal_name() const {
  return name_.Get();
}
inline void PrimitiveMeta::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrimitiveMeta::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.PrimitiveMeta.name)
}
inline void PrimitiveMeta::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.PrimitiveMeta.name)
}
inline void PrimitiveMeta::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.PrimitiveMeta.name)
}
inline std::string* PrimitiveMeta::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrimitiveMeta::release_name() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.PrimitiveMeta.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrimitiveMeta::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.PrimitiveMeta.name)
}

// string entity = 2;
inline void PrimitiveMeta::clear_entity() {
  entity_.ClearToEmpty();
}
inline const std::string& PrimitiveMeta::entity() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.entity)
  return _internal_entity();
}
inline void PrimitiveMeta::set_entity(const std::string& value) {
  _internal_set_entity(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.entity)
}
inline std::string* PrimitiveMeta::mutable_entity() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.PrimitiveMeta.entity)
  return _internal_mutable_entity();
}
inline const std::string& PrimitiveMeta::_internal_entity() const {
  return entity_.Get();
}
inline void PrimitiveMeta::_internal_set_entity(const std::string& value) {
  
  entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrimitiveMeta::set_entity(std::string&& value) {
  
  entity_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.PrimitiveMeta.entity)
}
inline void PrimitiveMeta::set_entity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.PrimitiveMeta.entity)
}
inline void PrimitiveMeta::set_entity(const char* value,
    size_t size) {
  
  entity_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.PrimitiveMeta.entity)
}
inline std::string* PrimitiveMeta::_internal_mutable_entity() {
  
  return entity_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrimitiveMeta::release_entity() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.PrimitiveMeta.entity)
  return entity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrimitiveMeta::set_allocated_entity(std::string* entity) {
  if (entity != nullptr) {
    
  } else {
    
  }
  entity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), entity,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.PrimitiveMeta.entity)
}

// .puppet.puppet_proto.BodyGroup body_group = 3;
inline void PrimitiveMeta::clear_body_group() {
  body_group_ = 0;
}
inline ::puppet::puppet_proto::BodyGroup PrimitiveMeta::_internal_body_group() const {
  return static_cast< ::puppet::puppet_proto::BodyGroup >(body_group_);
}
inline ::puppet::puppet_proto::BodyGroup PrimitiveMeta::body_group() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.body_group)
  return _internal_body_group();
}
inline void PrimitiveMeta::_internal_set_body_group(::puppet::puppet_proto::BodyGroup value) {
  
  body_group_ = value;
}
inline void PrimitiveMeta::set_body_group(::puppet::puppet_proto::BodyGroup value) {
  _internal_set_body_group(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.body_group)
}

// string frame_id = 4;
inline void PrimitiveMeta::clear_frame_id() {
  frame_id_.ClearToEmpty();
}
inline const std::string& PrimitiveMeta::frame_id() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.frame_id)
  return _internal_frame_id();
}
inline void PrimitiveMeta::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.frame_id)
}
inline std::string* PrimitiveMeta::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.PrimitiveMeta.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& PrimitiveMeta::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void PrimitiveMeta::_internal_set_frame_id(const std::string& value) {
  
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrimitiveMeta::set_frame_id(std::string&& value) {
  
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.PrimitiveMeta.frame_id)
}
inline void PrimitiveMeta::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.PrimitiveMeta.frame_id)
}
inline void PrimitiveMeta::set_frame_id(const char* value,
    size_t size) {
  
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.PrimitiveMeta.frame_id)
}
inline std::string* PrimitiveMeta::_internal_mutable_frame_id() {
  
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrimitiveMeta::release_frame_id() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.PrimitiveMeta.frame_id)
  return frame_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrimitiveMeta::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    
  } else {
    
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.PrimitiveMeta.frame_id)
}

// string reference_frame_id = 5;
inline void PrimitiveMeta::clear_reference_frame_id() {
  reference_frame_id_.ClearToEmpty();
}
inline const std::string& PrimitiveMeta::reference_frame_id() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
  return _internal_reference_frame_id();
}
inline void PrimitiveMeta::set_reference_frame_id(const std::string& value) {
  _internal_set_reference_frame_id(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
}
inline std::string* PrimitiveMeta::mutable_reference_frame_id() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
  return _internal_mutable_reference_frame_id();
}
inline const std::string& PrimitiveMeta::_internal_reference_frame_id() const {
  return reference_frame_id_.Get();
}
inline void PrimitiveMeta::_internal_set_reference_frame_id(const std::string& value) {
  
  reference_frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrimitiveMeta::set_reference_frame_id(std::string&& value) {
  
  reference_frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
}
inline void PrimitiveMeta::set_reference_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  reference_frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
}
inline void PrimitiveMeta::set_reference_frame_id(const char* value,
    size_t size) {
  
  reference_frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
}
inline std::string* PrimitiveMeta::_internal_mutable_reference_frame_id() {
  
  return reference_frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrimitiveMeta::release_reference_frame_id() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
  return reference_frame_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrimitiveMeta::set_allocated_reference_frame_id(std::string* reference_frame_id) {
  if (reference_frame_id != nullptr) {
    
  } else {
    
  }
  reference_frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reference_frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.PrimitiveMeta.reference_frame_id)
}

// .puppet.puppet_proto.Timestamp timestamp = 6;
inline bool PrimitiveMeta::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool PrimitiveMeta::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const ::puppet::puppet_proto::Timestamp& PrimitiveMeta::_internal_timestamp() const {
  const ::puppet::puppet_proto::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::puppet::puppet_proto::Timestamp&>(
      ::puppet::puppet_proto::_Timestamp_default_instance_);
}
inline const ::puppet::puppet_proto::Timestamp& PrimitiveMeta::timestamp() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.timestamp)
  return _internal_timestamp();
}
inline void PrimitiveMeta::unsafe_arena_set_allocated_timestamp(
    ::puppet::puppet_proto::Timestamp* timestamp) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:puppet.puppet_proto.PrimitiveMeta.timestamp)
}
inline ::puppet::puppet_proto::Timestamp* PrimitiveMeta::release_timestamp() {
  
  ::puppet::puppet_proto::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::puppet::puppet_proto::Timestamp* PrimitiveMeta::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:puppet.puppet_proto.PrimitiveMeta.timestamp)
  
  ::puppet::puppet_proto::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline ::puppet::puppet_proto::Timestamp* PrimitiveMeta::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<::puppet::puppet_proto::Timestamp>(GetArena());
    timestamp_ = p;
  }
  return timestamp_;
}
inline ::puppet::puppet_proto::Timestamp* PrimitiveMeta::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:puppet.puppet_proto.PrimitiveMeta.timestamp)
  return _internal_mutable_timestamp();
}
inline void PrimitiveMeta::set_allocated_timestamp(::puppet::puppet_proto::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:puppet.puppet_proto.PrimitiveMeta.timestamp)
}

// float confidence = 7;
inline void PrimitiveMeta::clear_confidence() {
  confidence_ = 0;
}
inline float PrimitiveMeta::_internal_confidence() const {
  return confidence_;
}
inline float PrimitiveMeta::confidence() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.confidence)
  return _internal_confidence();
}
inline void PrimitiveMeta::_internal_set_confidence(float value) {
  
  confidence_ = value;
}
inline void PrimitiveMeta::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.confidence)
}

// bool valid = 8;
inline void PrimitiveMeta::clear_valid() {
  valid_ = false;
}
inline bool PrimitiveMeta::_internal_valid() const {
  return valid_;
}
inline bool PrimitiveMeta::valid() const {
  // @@protoc_insertion_point(field_get:puppet.puppet_proto.PrimitiveMeta.valid)
  return _internal_valid();
}
inline void PrimitiveMeta::_internal_set_valid(bool value) {
  
  valid_ = value;
}
inline void PrimitiveMeta::set_valid(bool value) {
  _internal_set_valid(value);
  // @@protoc_insertion_point(field_set:puppet.puppet_proto.PrimitiveMeta.valid)
}

// map<string, string> tags = 20;
inline int PrimitiveMeta::_internal_tags_size() const {
  return tags_.size();
}
inline int PrimitiveMeta::tags_size() const {
  return _internal_tags_size();
}
inline void PrimitiveMeta::clear_tags() {
  tags_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PrimitiveMeta::_internal_tags() const {
  return tags_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
PrimitiveMeta::tags() const {
  // @@protoc_insertion_point(field_map:puppet.puppet_proto.PrimitiveMeta.tags)
  return _internal_tags();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PrimitiveMeta::_internal_mutable_tags() {
  return tags_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
PrimitiveMeta::mutable_tags() {
  // @@protoc_insertion_point(field_mutable_map:puppet.puppet_proto.PrimitiveMeta.tags)
  return _internal_mutable_tags();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace puppet_proto
}  // namespace puppet

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::puppet::puppet_proto::BodyGroup> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::puppet::puppet_proto::BodyGroup>() {
  return ::puppet::puppet_proto::BodyGroup_descriptor();
}
template <> struct is_proto_enum< ::puppet::puppet_proto::SourceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::puppet::puppet_proto::SourceType>() {
  return ::puppet::puppet_proto::SourceType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_puppet_2funiform_2eproto
