robot_qpos_source: control_intent
mujoco_model_xml: assets/unitree_g1/g1_mocap_29dof.xml
robot_name: unitree_g1
camera_body_name: pelvis
camera_distance: 2.0
camera_azimuth: 180.0
transparent_robot: 0

control_intent_bind_ip: 0.0.0.0
control_intent_bind_port: 16663

window_width: 1280
window_height: 720
render_hz: 60
print_stat: true
