loop_hz: 100
enable_mock_source: false

mock_human_bodies:
  - pelvis
  - spine3
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_foot
  - right_foot
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist

sources:
  - source_id: static_file_device
    source_type: external
    topic: static_file_device
    freshness_timeout_ms: 200
    history_size: 8

group_routing:
  - body_group: whole_body
    owner_source: static_file_device
    mode: gmr
    pipeline: gmr_pipeline
    backend: direct_backend

pipelines:
  - pipeline_id: gmr_pipeline
    plugin: gmr

backends:
  - backend_id: direct_backend
    type: direct_mapping

gmr_plugin:
  enabled: true
  backend: mujoco_se3
  robot_model_path: "assets/unitree_g1/g1_custom_collision_29dof.urdf"
  robot_model_xml_path: "assets/unitree_g1/g1_mocap_29dof.xml"
  ik_config_path: /data/open_src_code/GMR_custom/general_motion_retargeting/ik_configs/bvh_lafan1_to_g1.json
  actual_human_height: 1.75
  damping: 0.5
  max_iterations: 20
  use_velocity_limit: false
  integration_timestep: 0.01
  progress_threshold: 0.001

single_chain_ik:
  enabled: false
  chains:
    - body_group: right_arm
      ee_entity: right_wrist
      urdf_path: "assets/unitree_g1/g1_custom_collision_29dof.urdf"
      base_link: "torso_link"
      tip_link: "right_wrist_yaw_link"
      joint_names: [right_shoulder_pitch_joint, right_shoulder_roll_joint, right_shoulder_yaw_joint, right_elbow_joint, right_wrist_roll_joint, right_wrist_pitch_joint, right_wrist_yaw_joint]
      default_posture: [0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.0]
      min_position_limit: [-3.0892, -2.2515, -2.6180, -1.0472, -1.972222054, -1.614429558, -1.614429558]
      max_position_limit: [2.6704, 1.5882, 2.6180, 2.0944, 1.972222054, 1.614429558, 1.614429558]
      max_iterations: 10000
      timeout_sec: 0.003
      epsilon: 0.00001
      random_restart: false
      perturbation_max_attempts: 5
      perturbation_position_range: 0.01
      perturbation_angle_deg_range: 5.0

embosa_runtime:
  node_name: puppet_teleop_runtime
  input_topic_name: puppet_demo/primitive_frame
  output_control_intent_topic: puppet_demo/control_intent
  idle_sleep_ms: 2
  endpoints:
    inputs:
      - key: primitive_frame
        topic: puppet_demo/primitive_frame
        enabled: true
    outputs:
      - key: control_intent
        topic: puppet_demo/control_intent
        enabled: true
